ruby '2.1.0'
source 'https://rubygems.org'
gem 'aws-s3' 
gem 'data_mapper'
gem 'dm-migrations'
gem 'dm-redis-adapter'
gem 'foreman'
gem 'haml'
gem 'rake'
gem 'hiredis'
gem 'redis', '3.2.1'
gem 'to_regexp'
gem 'sass'
gem 'sinatra'
gem 'thin'
gem 'transmission_api'
gem 'twitter'